# Generated by Django 4.2.16 on 2024-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
