# Generated by Django 4.2.16 on 2024-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
